[package]
name = "feastore-proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "src/mod.rs"

[dependencies]
syn = { version = "2.0.63", features = ["extra-traits"] }
quote = "1.0.36"
